# -*- coding: utf-8 -*-
"""Calculator v1.0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12G7ujqy-_f192hXKv-ABgU4hBamgec6h
"""

#Write a basic python code to create a calculator which will perform addition , subtraction,multiplication and division
num1=int(input("Enter the first number"))
num2=int(input("Enter the second number"))
sum=num1+num2
diff=num1-num2
multi=num1*num2
div=num1/num2
print (f"The sum of two numbers {num1} and {num2} is {sum}")
print (f"The subtraction of two numbers {num1} and {num2} is {diff}")
print (f"The multiplication of two numbers {num1} and {num2} is {multi}")
print (f"The division of two numbers is {num1} and {num2} is {div}")